config/routes.rb
WhiteSpecApp::Application.routes.draw do
  resources :group_events
  
  root 'group_events#index'

end

app/models/group_event.rb
class GroupEvent < ActiveRecord::Base
	validates :event_duration, numericality: { only_integer: true }, allow_blank: true
	validates :event_start, :event_end, :event_duration, :name, :description, :location, presence: true, if: "published"
	validate :at_least_one_field
	after_save :update_time
	before_update :save_previous
	after_update :recheck_time
	
	def destroy
		update_columns(deleted: true)
	end
	
private
	def at_least_one_field
		if [event_start.to_s, event_end.to_s, event_duration.to_s, name, description, location].reject(&:blank?).size == 0
			errors[:base] << ("Please choose at least one field.")
		end
	end
	
	def update_time
		ar = [event_start.nil?, event_end.nil?, (event_duration.nil? || event_duration.zero?)]
		case ar
		when [false, true, false]
			update_column( :event_end, event_start + event_duration.day)
		when [false, false, true]
			update_column( :event_duration, (event_end - event_start).to_i)
		when [true, false, false]
			update_column( :event_start, event_end - event_duration.day)
		else
		end
	end
	
	def recheck_time
		ar = [(@before_update.event_start != event_start), (@before_update.event_end != event_end), (@before_update.event_duration != event_duration)]
		case ar
		when [false, true, false]
			update_column( :event_duration, (event_end - event_start).to_i)
		when [false, false, true]
			update_column( :event_end, event_start + event_duration.day)
		when [true, false, false]
			update_column( :event_end, event_start + event_duration.day)
		end
	end
	
	def save_previous
		@before_update = GroupEvent.find(id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/group_events_controller.rb
class GroupEventsController < ApplicationController
  before_action :set_group_event, only: [:show, :edit, :update, :destroy]

  # GET /group_events
  # GET /group_events.json
  def index
    @group_events = GroupEvent.where(deleted: false)
  end

  # GET /group_events/1
  # GET /group_events/1.json
  def show
  end

  # GET /group_events/new
  def new
    @group_event = GroupEvent.new
  end

  # GET /group_events/1/edit
  def edit
  end

  # POST /group_events
  # POST /group_events.json
  def create
    @group_event = GroupEvent.new(group_event_params)

    respond_to do |format|
      if @group_event.save
        format.html { redirect_to @group_event, notice: 'Group event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group_event }
      else
        format.html { render action: 'new' }
        format.json { render json: @group_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_events/1
  # PATCH/PUT /group_events/1.json
  def update
    respond_to do |format|
      if @group_event.update(group_event_params)
        format.html { redirect_to @group_event, notice: 'Group event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_events/1
  # DELETE /group_events/1.json
  def destroy
    @group_event.destroy
    respond_to do |format|
      format.html { redirect_to group_events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_event
      @group_event = GroupEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_event_params
	  begin
		json_params = ActionController::Parameters.new( JSON.parse(request.body.read) )
		return group_event_params_return(json_params)
	  rescue
		logger.error "No JSON params found"
	  end
	  group_event_params_return(params)
    end
	
	def group_event_params_return(p)
      p.require(:group_event).permit(:event_start, :event_end, :event_duration, :name, :description, :location, :published, :deleted)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_events_helper.rb
module GroupEventsHelper
end

app/views/group_events/_form.html.erb
<%= form_for(@group_event) do |f| %>
  <% if @group_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_event.errors.count, "error") %> prohibited this group_event from being saved:</h2>

      <ul>
      <% @group_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_start %><br>
    <%= f.date_select :event_start %>
  </div>
  <div class="field">
    <%= f.label :event_end %><br>
    <%= f.date_select :event_end %>
  </div>
  <div class="field">
    <%= f.label :event_duration %><br>
    <%= f.number_field :event_duration %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br>
    <%= f.check_box :deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/group_events/edit.html.erb
<h1>Editing group_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_event %> |
<%= link_to 'Back', group_events_path %>

app/views/group_events/index.html.erb
<h1>Listing group_events</h1>

<table>
  <thead>
    <tr>
      <th>Event start</th>
      <th>Event end</th>
      <th>Event duration</th>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
      <th>Published</th>
      <th>Deleted</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @group_events.each do |group_event| %>
      <tr>
        <td><%= group_event.event_start %></td>
        <td><%= group_event.event_end %></td>
        <td><%= group_event.event_duration %></td>
        <td><%= group_event.name %></td>
        <td><%= group_event.description %></td>
        <td><%= group_event.location %></td>
        <td><%= group_event.published %></td>
        <td><%= group_event.deleted %></td>
        <td><%= link_to 'Show', group_event %></td>
        <td><%= link_to 'Edit', edit_group_event_path(group_event) %></td>
        <td><%= link_to 'Destroy', group_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group event', new_group_event_path %>

app/views/group_events/new.html.erb
<h1>New group_event</h1>

<%= render 'form' %>

<%= link_to 'Back', group_events_path %>

app/views/group_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event start:</strong>
  <%= @group_event.event_start %>
</p>

<p>
  <strong>Event end:</strong>
  <%= @group_event.event_end %>
</p>

<p>
  <strong>Event duration:</strong>
  <%= @group_event.event_duration %>
</p>

<p>
  <strong>Name:</strong>
  <%= @group_event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group_event.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @group_event.location %>
</p>

<p>
  <strong>Published:</strong>
  <%= @group_event.published %>
</p>

<p>
  <strong>Deleted:</strong>
  <%= @group_event.deleted %>
</p>

<%= link_to 'Edit', edit_group_event_path(@group_event) %> |
<%= link_to 'Back', group_events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhiteSpecApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>